In [36]:
import numpy as np
from scipy import signal as sp

In [66]:
# linear convolution
x = np.array([1,2,3,4,5],dtype='float')
h = np.array([8,-2,5])
y = np.convolve(x,h)
print(y)
y = sp.lfilter(h,[1],np.hstack((x,[0,0])))
print(y)
y = sp.lfilter(h,[1],np.hstack((x,[1,2]))) # it is not circular!!
print(y)

[  8.  14.  25.  36.  47.  10.  25.]
[  8.  14.  25.  36.  47.  10.  25.]
[  8.  14.  25.  36.  47.  18.  39.]


In [17]:
# equivalent linear convolution in frequency domain
xx = np.hstack((x,[0,0]))
hh = np.hstack((h,[0 , 0, 0, 0]))
X = np.fft.fft(xx)
H = np.fft.fft(hh)
Y = X*H
y = abs(np.fft.ifft(Y))
print(y)

[  8.  14.  25.  36.  47.  10.  25.]


In [26]:
# circular convolution
x = np.array([1,2,3,4,5])
h = np.array([8,-2,5,8,-2]) # note that this is circular
y = np.convolve(x,h)
print(y)
y = np.convolve(h,x)
print(y)
y = np.convolve(x,h,'same')
print(y)
y = np.convolve(h,x,'same')
print(y)

[  8  14  25  44  61  30  51  32 -10]
[  8  14  25  44  61  30  51  32 -10]
[25 44 61 30 51]
[25 44 61 30 51]


In [43]:
X = np.fft.fft(np.hstack((x,[1,2])))
H = np.fft.fft(np.hstack((h,[8,-2,5,8])))
Y = X*H
y = abs(np.fft.ifft(Y))
print(y)

[ 72.  66.  96.  85.  79.  59.  83.]
